export {default as UserService} from './user.service'
export {default as AuthService} from './auth.service'
export {default as ProductService} from './product.service'
export {default as CategoryService} from './category.service'
export {default as TestimonialService} from './testimonial.service'
export {default as ContactService} from './contact.service'
export {default as OrderService} from './order.service'